# Imagem base do Node.js
FROM node:22

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos de dependências para cache de build
COPY package*.json ./

# Instala dependências e o nodemon globalmente
RUN npm install
RUN npm install -g nodemon

# Copia todo o restante do backend
COPY . .

# Expõe a porta que o backend vai usar
EXPOSE 5000

# Comando para iniciar o servidor com nodemon
CMD ["nodemon", "server.js"]
